version: '3'

services:
  mongo:
    image: mongo
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "3000:3000"
    restart: always
